crud_project/urls.py
from django.contrib import admin
from django.urls import path
from crud import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('create-student', views.create_student, name="create"),
    path('display-student', views.display_student, name="display"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('edit/<int:id>', views.edit_student, name="edit"),
    path('update/<int:id>', views.update_student, name="update"),
]

crud/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
	reg_no = models.CharField(max_length=50)
	name = models.CharField(max_length=100)
	mobile = models.CharField(max_length=10)
	email = models.EmailField(max_length=100)
	school = models.CharField(max_length=100)
	class Meta:
		db_table = 'student_master'

crud/forms.py
from django import forms
from crud.models import Student
class StudentForm(forms.ModelForm):
	class Meta:
		model = Student
		fields ="__all__"

crud/views.py
from django.shortcuts import render, redirect
from crud.forms import StudentForm
from crud.models import Student

# Create your views here.
def create_student(request):
	if request.method =="POST":
		form = StudentForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/display-student')
	else:
		form = StudentForm()
	return render(request, 'create-student.html',{'form':form})
def display_student(request):
	students = Student.objects.all()
	return render(request, 'display-student.html',{'students':students})
def delete(request, id):
	student = Student.objects.get(id=id)
	student.delete()
	return redirect('/display-student')
def edit_student(request, id):
	student = Student.objects.get(id=id)
	return render(request, 'edit-student.html', {'student':student})
def update_student(request, id):
	student = Student.objects.get(id=id)
	form = StudentForm(request.POST, instance = student)
	if form.is_valid():
		form.save()
		return redirect('/display-student')
	return render(request, 'edit-student.html',{'student':student})

templates/create-student.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title> Create Student </title>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<header class="jumbotron" style="padding: 2%;">
	<h2 class="text-center"> Create New Student </h2>
</header>
<div class="container">
	<form method="POST" action="/create-student">
		{% csrf_token %}
	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<div class="form-group">
				<label> Register Number </label>
				<input type="text" name="reg_no" id="id_reg_no" placeholder="Register Number" required class="form-control">
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
	</div>
		<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<div class="form-group">
				<label>  Student Name </label>
				<input type="text" name="name" id="id_name" placeholder="Student Name" required class="form-control">
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
	</div>

	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<div class="form-group">
				<label> Mobile </label>
				<input type="text" name="mobile" id="id_mobile" placeholder="Mobile" required class="form-control">
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
	</div>
	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<div class="form-group">
				<label>Email</label>
				<input type="email" name="email" id="id_email" placeholder="Email" required class="form-control">
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
	</div>
	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<div class="form-group">
				<label> School  </label>
				<input type="text" name="school" id="id_school" placeholder="School" required class="form-control">
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
	</div>
	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-block"> Register </button>
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"></div>
	</div>

	</form>

</div>
<!-- <form method="POST" action="/create-student">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> Submit </button>
</form> -->
</body>
</html>

templates/display-student.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title> Display Students </title>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>
<body>
	<header class="jumbotron" style="padding: 2%;">
		<h2 class="text-center"> Display Student Details </h2>
	</header>
	<div class="container">
	<div class="pull-right">
		<a href="{% url 'create' %}" class="btn btn-success"> Create New Student </a>
	</div>		
	<br/>
	<br/>
	<br/>
<table class="table table-hover table-bordered" id="showdetails">
	<thead>
		<tr>
			<th>Register No</th>
			<th>Name </th>
			<th> Mobile </th>
			<th> Email </th>
			<th>School</th>
			<th> Action </th>
		</tr>
	</thead>
	<tbody>
		{% for s in students %}
		<tr>
			<td> {{ s.reg_no }} </td>
			<td> {{ s.name }} </td>
			<td> {{ s.mobile }} </td>
			<td> {{ s.email }} </td>
			<td> {{ s.school }} </td>
			<td> 
				<a href="edit/{{ s.id }}" class="btn btn-xs btn-warning"> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> </a>
				<a href="delete/{{ s.id }}" class="btn btn-xs btn-danger"> <i class="fa fa-trash-o" aria-hidden="true"></i> </a> 
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
	</div>

	<script type="text/javascript">
$(document).ready( function () {
    $('#showdetails').DataTable();
} );
	</script>
</body>
</html>

templates/edit-student.html
<!DOCTYPE html>
<html>
<head>
	<title> Update Student</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<!-- jQuery library -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script> -->
<!-- Latest compiled JavaScript -->
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script> -->
</head>
<body>

<div class="container">
<br/>
<br/>
<br/>
<br/>
<form method="POST" action="/update/{{ student.id }}"> 
	{% csrf_token %}

	<div class="row">
		<div class="col-lg-4">
			<div class="form-group">
				<label> Register Number </label>
				<input type="text" name="reg_no" id="id_reg_no" placeholder="Register Number" required class="form-control" value="{{ student.reg_no}}">
			</div>
		</div>
		<div class="col-lg-4">
			<div class="form-group">
				<label> Student Name </label>
				<input type="text" name="name" id="id_name" value="{{ student.name}}" placeholder="Name" required class="form-control">
			</div>
		</div>
		<div class="col-lg-4">
			<div class="form-group">
				<label> Mobile </label>
				<input type="tel" name="mobile" value="{{ student.mobile}}" id="id_mobile" placeholder="Mobile" required class="form-control">
			</div>
		</div>
	</div>


	<div class="row">
		<div class="col-lg-4">
			<div class="form-group">
				<label> Email </label>
				<input type="email" name="email" value="{{ student.email}}" id="id_email" placeholder="Email" required class="form-control">
			</div>
		</div>
		<div class="col-lg-4">
			<div class="form-group">
				<label> School </label>
				<input type="text" name="school"  value="{{ student.school}}" id="id_school" placeholder="School" required class="form-control">
			</div>
		</div>
		<div class="col-lg-4"></div>
	</div>


	<div class="row">
		<div class="col-lg-4"></div>
		<div class="col-lg-4">
			<button type="submit" class="btn btn-success"> Update </button>
		</div>
		<div class="col-lg-4"></div>
	</div>

</form>


</div>

</body>
</html>